# Numpy Boolean Operators
-----
1. logical_and()
2. logical_or()
3. logical_not()

## Can we use and / or / not on array ?

In [1]:
import numpy as np

In [2]:
np_1d_array = np.array([10,20,30,40])

In [4]:
np_1d_array>15 and np_1d_array<35

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

> **not possible**?  then Solution is use logical_and,logical_or,logical_not

## logical_and

In [ ]:
np.logical_and(np_1d_array>15 ,np_1d_array<35) # condition

array([False,  True,  True, False])

In [ ]:
np_1d_array[np.logical_and(np_1d_array>15 ,np_1d_array<35)]

array([20, 30])

## logical_or

In [5]:
np.logical_or(np_1d_array>21,np_1d_array>35)

array([False, False,  True,  True])

In [ ]:
np_1d_array[np.logical_or(np_1d_array>21 ,np_1d_array>35)]

array([30, 40])

## logical_not

In [ ]:
np.logical_not(np_1d_array>21)

array([ True,  True, False, False])

In [ ]:
np_1d_array[np.logical_not(np_1d_array>21)]

array([10, 20])

## `Use Case:` Find Number of students received second class?. second class range is 50(inclusive) to 60(exclusive)


In [11]:
marks =np.array([10,40,20,52,55,70,80,90,25,65])

In [12]:
np.logical_and(marks >=50,marks<60)

array([False, False, False,  True,  True, False, False, False, False,
       False])

In [16]:
print(f"Total number of second class students are: {sum(np.logical_and(marks >=50,marks<60))}")

Total number of second class students are: 2
