# Numpy Boolean Operators
-----
1. logical_and()
2. logical_or()
3. logical_not()

## 1.  Can we use and / or / not on Numpy array ?

In [0]:
import numpy as np

In [0]:
np_1d_array = np.array([10,20,30,40])

In [0]:
np_1d_array>15 and np_1d_array<35

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

> **not possible**?  then Solution is use logical_and,logical_or,logical_not

## 2. logical_and

In [0]:
np.logical_and(np_1d_array>15 ,np_1d_array<35) # condition

array([False,  True,  True, False])

In [0]:
np_1d_array[np.logical_and(np_1d_array>15 ,np_1d_array<35)]

array([20, 30])

## 3. logical_or

In [0]:
np.logical_or(np_1d_array>21 ,np_1d_array>35)

array([False, False,  True,  True])

In [0]:
np_1d_array[np.logical_or(np_1d_array>21 ,np_1d_array>35)]

array([30, 40])

## 4. logical_not

In [0]:
np.logical_not(np_1d_array>21)

array([ True,  True, False, False])

In [0]:
np_1d_array[np.logical_not(np_1d_array>21)]

array([10, 20])